name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Ruby ${{ matrix.ruby }}, Rails ${{ matrix.rails }}
    continue-on-error: ${{ matrix.continue-on-error }}

    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.4", "3.3", "3.2"]
        rails: ["8.1", "8.0", "7.2", "7.1", "7.0"]
        continue-on-error: [false]
        include:
          - ruby: "3.4"
            rails: "main"
            continue-on-error: true
          - ruby: "head"
            rails: "main"
            continue-on-error: true

    runs-on: ubuntu-latest

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          SA_PASSWORD: yourStrongPassword123
          ACCEPT_EULA: Y
        ports:
          - 1433:1433

    env:
      RAILS_VERSION: ${{ matrix.rails }}
      MSSQL_USER: "sa"
      MSSQL_PASSWORD: "yourStrongPassword123"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install dependent libraries
        run: sudo apt install freetds-dev freetds-bin

      - name: Generate lockfile
        run: bundle lock

      - name: Set up Scenic
        run: bin/setup

      - name: Run tests
        run: bundle exec rake test
        continue-on-error: ${{ matrix.continue-on-error }}
